server:
  port: 8080
  #servlet:
    #context-path: /test
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zxt
    password: '#zx009900'
    url: jdbc:mysql://rm-wz9benc9m2l3knpn7yo.mysql.rds.aliyuncs.com/zxt?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
  cache:
    type: redis
  #redis配置
  redis:
    #Redis服务器地址
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    #Redis数据库索引（默认为0）
    database: 0
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 50
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        #连接池中的最大空闲连接
        max-idle: 20
    #连接超时时间（毫秒）
    timeout: 5000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springboot.hwzl.entity
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
weixin:
  accessTokenUrl: http://zl.wmxmt.cn/WechatInfo/GetAccessToken
  token: "BD20190819_Js18721121"
